after-login-command = []

after-startup-command = [
    'exec-and-forget borders active_color=0xff88c0d0 inactive_color=0xff4c566a width=5.0',
    'exec-and-forget open -a Obsidian',
    'exec-and-forget open -a Alacritty',
    'exec-and-forget open -a Zen',
    'exec-and-forget open -a Spotify',
    'workspace 3',
]

start-at-login = true
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 2
inner.vertical = 2
outer.left = 2
outer.bottom = 2
outer.top = 2
outer.right = 2

[mode.main.binding]
cmd-j = 'focus --boundaries-action wrap-around-the-workspace left'
cmd-k = 'focus --boundaries-action wrap-around-the-workspace down'
cmd-l = 'focus --boundaries-action wrap-around-the-workspace up'
cmd-semicolon = 'focus --boundaries-action wrap-around-the-workspace right'

cmd-shift-j = 'move left'
cmd-shift-k = 'move down'
cmd-shift-l = 'move up'
cmd-shift-semicolon = 'move right'

cmd-f = 'fullscreen'
cmd-r = 'mode resize'
cmd-s = 'layout v_accordion'               # 'layout stacking' in i3
cmd-w = 'layout h_accordion'               # 'layout tabbed' in i3
cmd-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3
cmd-shift-q = 'close'
cmd-shift-c = 'reload-config'

# Workspace 1: Notes
cmd-1 = 'workspace 1'
cmd-shift-1 = 'move-node-to-workspace 1'
ctrl-shift-1 = 'exec-and-forget open -a Obsidian'

# Workspace 2: Terminal
cmd-2 = 'workspace 2'
cmd-shift-2 = 'move-node-to-workspace 2'
cmd-enter = 'exec-and-forget open -a Alacritty'

# Workspace 3: Browser
cmd-3 = 'workspace 3'
cmd-shift-3 = 'move-node-to-workspace 3'
ctrl-shift-3 = 'exec-and-forget open -a Zen'

# Workspace 4: Editor
cmd-4 = 'workspace 4'
cmd-shift-4 = 'move-node-to-workspace 4'


# Workspace 5: ??
cmd-5 = 'workspace 5'
cmd-shift-5 = 'move-node-to-workspace 5'

# Workspace 6: ??
cmd-6 = 'workspace 6'
cmd-shift-6 = 'move-node-to-workspace 6'

# Workspace 7: Zoom
cmd-7 = 'workspace 7'
cmd-shift-7 = 'move-node-to-workspace 7'

# Workspace 8: VM
cmd-8 = 'workspace 8'
cmd-shift-8 = 'move-node-to-workspace 8'

# Workspace 9: Spotify 
cmd-9 = 'workspace 9'
cmd-shift-9 = 'move-node-to-workspace 9'
ctrl-shift-9 = 'exec-and-forget open -a Spotify'

# Workspace 10: Multi-app
cmd-0 = 'workspace 10'
cmd-shift-0 = 'move-node-to-workspace 10'

[mode.resize.binding]
j = 'resize width -50'
k = 'resize height +50'
l = 'resize height -50'
semicolon = 'resize width +50'
enter = 'mode main'
esc = 'mode main'


# Workspace 1: Notes
[[on-window-detected]]
if.app-id = 'md.obsidian'
run = "move-node-to-workspace 1"

# Workspace 2: Terminal 
[[on-window-detected]]
if.app-id = 'org.alacritty'
run = "move-node-to-workspace 2"

# Workspace 3: Browser 
[[on-window-detected]]
if.app-id = 'app.zen-browser.zen'
run = "move-node-to-workspace 3"

# Workspace 4: Editor Workspace
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = "move-node-to-workspace 4"

# Workspace 5: ?? 
# Workspace 6: ??

# Workspace 7: Zoom 
[[on-window-detected]]
if.app-id = 'us.zoom.xos'
run = "move-node-to-workspace 7"

# Workspace 8: VM
[[on-window-detected]]
if.app-id = 'com.utmapp.UTM'
run = "move-node-to-workspace 8"

# Workspace 9: Spotify 
[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 9"

[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'

6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
10 = 'secondary'
