[general]
import = ["~/.config/alacritty/alacritty-themes/tokyo_night.toml"]

[window]
padding.x = 10
padding.y = 10
opacity = 0.8


[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Shift|Alt"

