[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night.toml"]

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"
opacity = 0.8

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14